### ISSUE TITLE
process.env changes not seen by subsequent steps

### ISSUE THREAD

**Issue by MSP-Greg** [actions/toolkit#102]
New to to node, and haven't coded that much in ES5/ES6.  But...

`core.addPath` certainly works in that it's changes to `process.env['PATH']` are visible in subsequent steps.

I'm trying to remove some items from the Windows PATH, and also create another env variable.  They log fine in the *.js for the action, but subsequent steps are not seeing the changes.  But they are seeing changes I've made using `core.addPath`...

Not sure where to post this...

**Comment by damccorm** [comment]
Yep, in general env changes from one step shouldn't affect future steps so that each action can expect its own clean environment. If you need env var changes to propogate you can use [`exportVariable`](https://github.com/actions/toolkit/blob/99d3ad0a6473e7e7906681627a450150a772ee1d/packages/core/src/core.ts#L37) from the core library. That should include any changes to the PATH variable - we mostly provide `addPath` as a convenience function to handle things like path separators in a platform agnostic way since its a common need in all of our setup actions (and other contexts)

**Comment by MSP-Greg** [comment]
@damccorm 

Thanks for pointing that out, even though I've looked at the file, I missed it.  Not sure why that can't be done in the actions *.js file, as the call to `exportVariable` worked, but it just replaced the same code it performs.

I assume something with scoping, I'll look over the code some more...
