### ISSUE TITLE
Exec commands are trimmed in the log output

### ISSUE THREAD

**Issue by xt0rted** [actions/toolkit#132]
I'm testing out the `exec` package and what I'm noticing is all of the commands that I execute are logged but the first 2 characters of the command are being cut off.

- **Runner version**: 2.157.5
- **`@actions/exec` version**: 1.0.1

This is the code I'm executing:

```ts
await exec.exec("dotnet-format", ["--check", "--dry-run"], options);
```

In the raw log I'm seeing:

```
[command]dotnet tool install -g dotnet-format
```

But in the styled log I'm seeing:

![image](https://user-images.githubusercontent.com/831974/64752565-17e99600-d4ee-11e9-8311-848c5957c571.png)

**Comment by 1138-4EB** [comment]
I think I'm having the same issue. For example:

- From https://github.com/1138-4EB/actions/commit/92a6da98ce69920b56e9d2b06b3a8b18be7ce88a/checks#step:2:38 to line 49, the first character (`C` or `/`) is missing.
- From https://github.com/1138-4EB/actions/commit/92a6da98ce69920b56e9d2b06b3a8b18be7ce88a/checks#step:2:50 to line 54, `[0m` is shown instead of the first character.

It might be related to colouring. `[command]` lines are coloured automatically by default.

**Comment by bryanmacfarlane** [comment]
The UI issue was fixed. (1264 mentioned above)

**Comment by yaananth** [comment]
☝️  that's a different issue than the linked one. `[command]` issue is fixed.
@1138-4EB  the issue is because..
We support https://en.wikipedia.org/wiki/ANSI_escape_code#3/4_bit
The log has:
`ESC[mCompiling into vunit_lib` 

`ESC[m` isn't something we support.

I logged an issue to ignore such commands.
We will get it fixed

**Comment by 1138-4EB** [comment]
@yaananth, thanks for explaining! Actually, that log is generated with [tartley/colorama](https://github.com/tartley/colorama). If you think that (apart/instead of working around) it is worth having colorama enhanced, please let me know. For example, ensuring that `ESC[0m` is produced instead of `ESC[m`.

**Comment by yaananth** [comment]
@1138-4EB That should be okay, if the terminal responds well, I don't think we expect you to change it. Logs should just ignore things that don't matter to it :)
We have PR up to address this.
