### ISSUE TITLE
Prevent concurrent workflows run on a given filtered tag/branch

### ISSUE THREAD

**Issue by yvele** [actions/toolkit#137]
We can [filter](https://help.github.com/en/articles/configuring-a-workflow#filtering-for-specific-branches) workflows to run on specific branches and also [limit](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstrategymax-parallel) the maximum number of jobs that can run simultaneously when using a `matrix` job strategy.

But I would like to **limit concurrent workflows** given on given `branches` or `tags` filters.

For example:
 - Branch `develop`: Only a single workflow run at a time
 - Branch `master`: Only a single workflow run at a time
 - Tag `v*`: Only a single workflow run at a time

```yaml
on:
  push:
    max-parallel: 1 # <-----
    branches:    
      - develop
      - master 
    tags:        
      - 'v*'
```

Or even better, apply the concurrent limit on given steps (i.e. the deployment step, to avoid deployment collisions..).

------------------------------

Note: CircleCI has a similar feature, but its implementation is not great and some people are complaining, see https://discuss.circleci.com/t/prevent-concurrent-builds-of-a-branch/1142 and https://discuss.circleci.com/t/sequentially-running-workflows/23288

> I have two different product branches (master & integration) that, as part of their deploy step, perform a deployment to Amazon ElasticBeanstalk. But the deployment fails when another deployment is in-progress.
> 
> I’d like the ability to prevent multiple concurrent builds of the same branch, in the same project. The builds would sit “queued” until the running build on that branch completes.

**Comment by bryanmacfarlane** [comment]
Not a toolkit issue but I'm creating a feedback item for the team working on the lang.

**Comment by ethomson** [comment]
Hi - thanks for trying GitHub Actions, and I appreciate the suggestion.    We've created a feedback item for the team working on the language.

I’m going to close this issue since it doesn't apply to the GitHub Actions toolkit itself.  But if you have any other questions or problems with GitHub Actions, I’d encourage you to ask on the **[GitHub Actions Community Forum](https://github.community/t5/GitHub-Actions/bd-p/actions)**, where the GitHub Actions product and support teams can assist.  You can also contact [GitHub Support](https://github.com/contact) for assistance.

Thanks for trying GitHub Actions!

**Comment by fkirc** [comment]
I published an Action that prevents concurrent workflow-runs: https://github.com/fkirc/skip-duplicate-actions
This Action can be combined with conditional checks for branches or tags. 
You may give it a try if this is still an issue.
