### ISSUE TITLE
optional read/write permission for forked repos

### ISSUE THREAD

**Issue by ibakshay** [actions/toolkit#159]
Hi,
I am using `GITHUB_TOKEN` secret to make authenticated GitHub API calls on behalf of an action. 

I am the maintainer of [CLA Assistant](https://github.com/cla-assistant/cla-assistant) OAuth App and we are developing `CLA Lite GitHub Action`. The  contributors data will be stored in the file-system (json file) inside the repository of where the `CLAAssistant.yml` is configured. 

 However, we just come to know that there is only **read Access**  but **no write access** when there is a Pull Request from the forked Repository, So the contributors details from the forked repository cannot be written in a file of the base repository since The permissions for the GITHUB_TOKEN in forked repositories is **read-only**.

It will be great If the `GITHUB_TOKEN` permission can be optionally **read/write** and default is only **read** for the forked repos. And also, please suggest If there is any other work around for this use-case. 

![Screen Shot 2019-09-23 at 14 45 17](https://user-images.githubusercontent.com/33329946/65426593-ca83f780-de10-11e9-8138-ac658a0af488.png)

**Comment by ethomson** [comment]
Hi @ibakshay - thanks for the question.  It looks like you’ve also posted this on the [GitHub Actions Community Forum](https://github.community/t5/GitHub-Actions/optional-read-write-permission-for-forked-repos/m-p/32495#M1159) which is a better place to discuss this question.  Since this repository contains the toolkit for developing new actions, I’m going to close this and we can continue discussion on the forum.

Thanks for trying GitHub Actions!
