### ISSUE TITLE
Naming of exec

### ISSUE THREAD

**Issue by ioquatix** [actions/toolkit#182]
It's a little bit confusing because `exec` in unix has a different meaning from exec in this module. Additionally writing `exec.exec` just looks weird. I wish you consider improved name, e.g. `exec.system` which is more in line with existing naming conventions.

**Comment by bryanmacfarlane** [comment]
Thanks for logging an issue!

Since this is a node based lib, it was following the [node naming pattern of exec](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback).

Regarding exec.exec, it doesn't have to be that. e.g. in typescript ...

```javascript
import {exec} from '@actions/exec/lib/exec'

// then it's just
exec(...)
```

or

```javascript
// import exec module
import * as em from '@actions/exec'

em.exec(...)
```

This is public and released so we probably won't be renaming it.  Thanks for logging though!

**Comment by ioquatix** [comment]
I see `exec` follows the nodejs pattern. That makes sense. But their module is not named after a function, it's named after a noun `child_process`. So, to extrapolate that, naming the module after a verb is maybe less than clear, at least in this context. Maybe such a useful function doesn't need to sit in it's own module, but can be moved into core, where it would become `core.exec`.
