### ISSUE TITLE
Workflow to release a GitHub Action

### ISSUE THREAD

**Issue by crazy-max** [actions/toolkit#234]
Hi guys,

I have [created a workflow](https://gist.github.com/crazy-max/f347632c53c81271906697bdb40e8074) to automate the creation of branches and tags when you release your GitHub Action according to [your recommendations](https://github.com/actions/toolkit/blob/master/docs/action-versioning.md).

Maybe I could create a PR to include my gist in your action versioning page if you are interested?

**Comment by bryanmacfarlane** [comment]
versioning is update.  the main problem here is you don't always want to create a release branch until you're going to create a new major version with master being the current latest version (see doc updates).  That along with the infrequency of creating a major version, makes it a very infrequent trivial command line.  It seems like the authors to decision to create another branch instead of something that's always done via automation.

**Comment by bryanmacfarlane** [comment]
closing with explanation ☝️
