### ISSUE TITLE
Delete Artifacts using @actions/artifact

### ISSUE THREAD

**Issue by konradpabjan** [actions/toolkit#380]
It is currently possible to delete an artifact that is associated with a workflow run using the GitHub API: https://developer.github.com/v3/actions/artifacts/#delete-an-artifact

This API is limited though because an artifact is not available until after a run is complete

The `@actions/artifact` package should add a public `deleteArtifact()` method that will allow users to delete an artifact during a run

This will make it easier to support certain types types of scenarios such as retention

**Comment by bradennapier** [comment]
Agreed - additionally the artifacts using the lib are scoped to the workflow only so there are some other challenges .  I wanted to make sure linting occurred when a forked PR was created and ended up needing to do some magic with the rest api directly to get it all working.

https://github.com/bradennapier/eslint-plus-action/blob/master/src/artifacts.ts

This type of application should be natively supported without question - especially since it solves the security problem, but it is also an example of how you can use the rest api for it.   I have some extra pieces in there which may not be necessary but I haven't had a change to test without yet (I am deleting then remaking each time to make sure as I wasn't positive if it would overwrite if different workflows were creating them).

**Comment by robinxb** [comment]
+1 for deploying some artifacts when using other deployment. Now I have to sleep for few seconds to make this work.

**Comment by sefasenturk95** [comment]
When is this expected to be implemented?

**Comment by muzimuzhi** [comment]
> This API is limited though because an artifact is not available until after a run is complete

This limitation is removed in [`@actions/artifact@v2`](https://github.com/actions/toolkit/blob/5430c5d84832076372990c7c27f900878ff66dc9/packages/artifact/README.md):

> Improvements
> [...]
> 2\. Once uploaded, an Artifact ID is returned and Artifacts are immediately available in the UI and [REST API](https://docs.github.com/en/rest/actions/artifacts). Previously, you would have to wait for the run to be completed before an ID was available or any APIs could be utilized.
> 3\. Artifacts can now be downloaded and deleted from the UI before the entire workflow run finishes.
