### ISSUE TITLE
exec silent for the command and separate silent for std*

### ISSUE THREAD

**Issue by ghstahl** [actions/toolkit#389]
Calling the az cli there are 2 types of secret leakage;
1. on the command line
2. via az cli stdout, ...

I have a case where a secret is leaked on the command-line but the az cli stdout is OK, and vice versa. 

Thanks to the ExecOptions that allowed me to hook std*, I was able to have separate silent options;
```
async function executeCliCommandWithReturn(
  cliPath: string,
  command: string,
  cmdSilent: boolean,
  stdoutSilent: boolean
): Promise<string> {
  try {
    let myOutput = ''
    let myError = ''

    const options: ExecOptions = {
      silent: cmdSilent,
      listeners: {
        stdout: (data: Buffer) => {
          if (!stdoutSilent) {
            process.stdout.write(data)
          }
          myOutput += data.toString()
        },
        stderr: (data: Buffer) => {
          if (!stdoutSilent) {
            process.stderr.write(data)
          }
          myError += data.toString()
        }
      }
    }

    await exec.exec(`"${cliPath}" ${command}`, [], options)
    if (myError.length > 0) {
      throw new Error(myError)
    }
    return myOutput
  } catch (error) {
    throw new Error(error)
  }
}
```
Could you consider having this option as part of @actions/exec, as I am not the only one that will run into this generic issue.

**Comment by thboop** [comment]
@ghstahl if you register the secret as a secret you shouldn't be seeing any leakage. I'm going to close this issue out, but if you can reproduce this please let me know and we will fix it asap.

We also have the ability to run [exec as silent](https://github.com/actions/toolkit/blob/main/packages/exec/src/interfaces.ts#L13), which I think this issue is requesting


I'm going to close this out, but feel free to reopen if its still an issue for you
