### ISSUE TITLE
permanent artifacts

### ISSUE THREAD

**Issue by JoseQuintas** [actions/toolkit#690]
I create a workflow:
- build mingw pack
- build harbour compiler
- build libraries

But I would like separated process.
I do not need allways to create the mingw pack, nor the build compiler.
I would like to use the artifact created a month ago, without recreate it on each execution.
Is this possible?

**Comment by konradpabjan** [comment]
Not currently possible. This is equivalent to directly downloading an artifact that was built using another workflow and due to the permissions of the `GITHUB_TOKEN` it is not possible. You could use some of our APIs along with a PAT with extra permissions to download an artifact from a previous workflow: https://docs.github.com/en/rest/reference/actions#download-an-artifact  But we don't have a first-party solution for you to do that (some extra options or anything with `upload-artifact` as an example).

https://github.com/actions/download-artifact/issues/3

**Comment by JoseQuintas** [comment]
What about project with sub-projects?
sub-projects are available to project, and all projects are on same account.
source code of workflows are visible to master, may be a situation where could be possible to share workflows and results.
Not sure if this is already available.

**Comment by JoseQuintas** [comment]
May be I found an option, but not sure how to use it.
To delete a release, I use git push --delete origin tag_name
Is there a git pull to download the release?

**Comment by JoseQuintas** [comment]
Now I found the solution, but I need help.
Using powershell I have easy access to all things 
I have lists, I have all information., including direct links.
But to download, I need authentication.
1) How authenticate using powershell (seems is using Headers)?
2) Is there an action to download from a direct link?

**Comment by JoseQuintas** [comment]
action-download already have the feature, do not need to create anything new, it accepts repository name
